# Generated by Django 2.1 on 2018-08-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20, unique=True)),
                ('userPasswd', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('userImg', models.CharField(max_length=150)),
                ('userGender', models.BooleanField(default=True)),
                ('userBirth', models.DateField(max_length=20)),
                ('userContent', models.TextField(default='nothing...')),
                ('userToken', models.CharField(max_length=50)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
