# Generated by Django 2.1 on 2018-09-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocalApp', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='_user_contacts_+', to='SocalApp.User'),
        ),
    ]
