# Generated by Django 2.1 on 2018-09-08 15:04

import SocalApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocalApp', '0003_user_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='内容')),
                ('head_img', models.ImageField(default='', upload_to=SocalApp.models.user_directory_path)),
                ('publish_data', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('hidden', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('priority', models.IntegerField(default=1000, verbose_name='优先级')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocalApp.User', verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocalApp.Article')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_comment', to='SocalApp.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocalApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='ThumbUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocalApp.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocalApp.User')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(default='', to='SocalApp.Category', verbose_name='标签'),
        ),
    ]
