# Generated by Django 2.1 on 2018-09-11 16:53

import SocalApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocalApp', '0005_auto_20180911_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(blank=True, default='', upload_to=SocalApp.models.user_directory_path),
        ),
    ]
