# Generated by Django 2.1 on 2018-09-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocalApp', '0006_auto_20180912_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(blank=True, default='', upload_to='img'),
        ),
    ]
