# Generated by Django 2.1 on 2018-09-11 17:34

import SocalApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocalApp', '0007_auto_20180912_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(blank=True, default='', upload_to=SocalApp.models.upload_to),
        ),
    ]
