# Generated by Django 2.1 on 2018-09-18 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocalApp', '0009_auto_20180919_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='SocalApp.Category', verbose_name='标签'),
        ),
    ]
